server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:markethub}
    username: ${DB_USERNAME:markethub_user}
    password: ${DB_PASSWORD:markethub_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_password}
      timeout: 2s
      ssl:
        enabled: ${SPRING_REDIS_SSL_ENABLED:false}
        bundle: ${SPRING_REDIS_SSL_BUNDLE:}


  cache:
    type: redis

jwt:
  secret: ${JWT_SECRET:dev-only-markethub-jwt-secret-key-32bytes-minimum}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    email: ${APP_ADMIN_EMAIL:admin@markethub.local}
    password: ${APP_ADMIN_PASSWORD:admin12345}
    first-name: admin
    last-name: admin
    birth-date: 1970-01-01

  product:
    images:
      max-file-size-bytes: ${APP_PRODUCT_IMAGES_MAX_FILE_SIZE_BYTES:5242880}
      max-images-per-product: ${APP_PRODUCT_IMAGES_LIMIT:5}
      allowed-content-types: ${APP_IMAGES_ALLOWED_TYPES:image/jpeg,image/png,image/webp}

  minio:
    endpoint: ${APP_MINIO_ENDPOINT:http://minio:9000}
    access-key: ${APP_MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${APP_MINIO_SECRET_KEY:minioadmin}
    bucket: ${APP_MINIO_BUCKET:markethub-images}

  rate-limit:
    enabled: true
    request-limit: ${REQUEST_LIMIT:10}
    window-size: ${WINDOW_SIZE:1m}
